### ISSUE TITLE
develop a push-button CloudFormation template to deploy an EKS cluster with SPS

### ISSUE THREAD

**Issue by pymonger** [unity-sds/unity-on-demand#13]
# Background
In our recent tagup with Wayne Burke and the ITSD folks who will help us develop and maintain our On-Demand AWS Quick Start, a starting point for them would be to deliver a push-button CloudFormation template that will:
1. deploy an EC2 instance with requisite instance role to deploy AWS resources
1. deploy an EKS cluster via `act`
1. deploy SPS onto that EKS cluster via `terraform`

# Task
This task here is to develop this push-button CloudFormation template in coordination with U-CS (responsible for the EKS cluster provisioning) and U-SPS (responsible for deploying SPS) with a focus on IaaS code reuse and modularity.

# DoD
- CloudFormation template that performs the push-button deployment as described above
- documentation on usage of this template
- demo to On-Demand team

**Comment by riverma** [comment]
Hey @pymonger - please consider submitting the documentation to a location within the U-CS docs space: https://unity-sds.gitbook.io/docs/developer-docs/common-services

**Comment by pymonger** [comment]
# Status update
Initial implementation and end-to-end deployment test completed. All testing was performed in the MAAP-HEC MCP account, a non-Unity MCP account. The CloudFormation template (https://github.com/unity-sds/unity-on-demand-cloudformation/blob/b17b793ad265e1d3e89f5fe0034bdfdc14849c91/templates/unity_deployer_instance-act.yaml) successfully:

1. deployed a deployer/management EC2 instance
1. invoked `act` via the `unity-cs-infra:main` docker image to deploy an EKS cluster (underlying calls to eksctl)
1. provisioned the EKS cluster with necessary `kubectl` configuration to enable k8s worker node access to the external network, access to the cluster for users with both `mcp-tenantDeveloper` and `mcp-tenantOperator` roles, and installed the `aws-ebs-csi-driver` to allow for dynamic provisioning of EBS-backed PVCs
1. provisioned SPS onto the EKS cluster using terraform

# Screenshots
![Screen Shot 2022-12-22 at 4.11.36 PM.png](https://images.zenhubusercontent.com/6272d822eec052179b4b8a8a/fa05084e-60ea-4c2e-ab9c-1052118a0697)
![Screen Shot 2022-12-22 at 4.12.16 PM.png](https://images.zenhubusercontent.com/6272d822eec052179b4b8a8a/ea4f42d7-b475-4705-bdd8-df2c121cf6bc)
![Screen Shot 2022-12-22 at 4.12.29 PM.png](https://images.zenhubusercontent.com/6272d822eec052179b4b8a8a/9a585457-54fb-4968-8f5d-52ed19d0c3f0)

# TODO
Things left to do to complete this ticket:
- clean out hard-coded values and wire them out through CloudFormation parameters (e.g. subnet IDs)
- test in a Unity MCP account (Unity DEV)
- documentation

**Comment by galenatjpl** [comment]
This ticket is completed. Closing..
