### ISSUE TITLE
As the OD REST API, I want to make pre-warm calls to the SPS REST API

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-on-demand#21]
These calls should be independent of the actual SPS implementation/technology.  

This will be (for release 23.1) the basic form of the call, which only includes `node_count` in the request.
A prerequisite of this ticket, is having the SPS API deployed.

**Comment by pymonger** [comment]
Done see: https://github.com/unity-sds/unity-on-demand/blob/main/CHANGELOG.md#unity-release-231---2023-04-07
