### ISSUE TITLE
[Documentation]: Document OD preWarm REST API

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-on-demand#24]
Document the possible API methods for the on-demand prewarm call

**Comment by galenatjpl** [comment]
Only thing left to do would be to finish of the passing of the OpenAPI spec to gitbook, so that it shows up in our docs there.

**Comment by galenatjpl** [comment]
@pymonger  investigating a "file is too large" error, when uploading.  He's cleaning up gitbook https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/~/changes/234/developer-docs/on-demand

**Comment by pymonger** [comment]
Done. See https://github.com/unity-sds/unity-on-demand/blob/main/CHANGELOG.md#unity-release-231---2023-04-07.
