### ISSUE TITLE
Remove deployment of services from CloudFormation

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-on-demand#26]
Remove:
- on-demand API deployment

Basically, decouple everything that's not "stand up the Management Console EC2" from the quickstart/cloudformation

Acceptance Criteria:
- [x] CloudFormation is able to instantiate the Management Console EC2 instance
- [x] other deployments such as EKS, and the on-demand API serverless code is not in the cloudFormation anymore

**Comment by pymonger** [comment]
Terraform creation: [unity-on-demand-api](https://github.com/unity-sds/unity-on-demand-api/pull/3)
