### ISSUE TITLE
CloudFormation to use new Management Console binary

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-on-demand#28]
Acceptance Criteria:
- [x] The CloudFormation should launch the EC2
- [x] The CloudFormation should contain proper downloading of MC zip file
- [x] The CloudFormation should invoke the MC bootstrap actions 
      This will run the actions in this ticket:  https://github.com/unity-sds/unity-cs/issues/222 (BASELINE RESOURCES)
- [x] Verify that the MC bootstrap actions are properly executed in the context of the deployment instance

**Comment by pymonger** [comment]
Implemented and tested via https://github.com/unity-sds/unity-on-demand-cloudformation/pull/1. See the PR for test artifacts.
